cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      accessKey: AKIASN2O7DKQSZNGCROA
      secretKey: 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
dragonglass:
  queue:
    topic: mahajanashuoutlookcom_c83c10f093864a06bd3dca956c5b5fcd.fifo
logging.file: C:/logs/auctioneer-event.log
logging:
  file:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: DEBUG
    guru.springframework.controllers: DEBUG
    com.opencrowd.dragonglass: INFO
    org.apache.kafka: INFO